### ISSUE TITLE
integrate a way to collect anonymous data to measure the plugin's effectiveness

### ISSUE THREAD

**Issue by damevski** [vcu-swim-lab/stack-intheflow#34]
figure out if there is a standard way to do this...

**Comment by jeetgajjar** [comment]
http://stackoverflow.com/questions/32294213/intellij-idea-plugin-development-log-from-within-plugin
This link provide some insight into logging.


Subtask- create notification dialog on opting out of logging for privacy's sake.
If we're to distro this for real testing, we should implement logging. Otherwise this issue is moot in my opinion.

Questions: What do we want to log?
Time frame?

**Comment by Zerthick** [comment]
Implemented by @carpentercr
